---
- name: Apache server uninstall
  hosts: web

  tasks:
  - name: stop and disable Apache
    service:
      name: httpd
      enabled: false
      state: stopped

  - name: disable firewalld permits of http service
    firewalld:
      service: http
      state: absent
      immediate: yes
      
  - name: stop and disable firewalld
    service:
      name: firewalld
      enabled: false
      state: stopped
            
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: absent
      
  - name: latest Apache version installed
    yum:
      name: httpd
      state: absent
